# Generated by Django 3.0.3 on 2020-08-02 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Doctors',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=30)),
                ('Age', models.CharField(max_length=2)),
                ('Qualification', models.CharField(max_length=30)),
                ('Experience', models.CharField(max_length=2)),
                ('Gender', models.CharField(max_length=15)),
                ('Specialization', models.CharField(max_length=30)),
                ('Hospital', models.CharField(max_length=50)),
                ('Address', models.CharField(max_length=100)),
                ('Phone', models.CharField(max_length=15)),
                ('Email', models.CharField(max_length=30)),
                ('From', models.TimeField()),
                ('To', models.TimeField()),
            ],
        ),
    ]
