# Generated by Django 3.0.3 on 2020-08-03 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Answers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=30)),
                ('Hospital', models.CharField(max_length=50)),
                ('Phone', models.CharField(max_length=15)),
                ('Problem', models.CharField(max_length=2000)),
                ('Answer', models.CharField(max_length=2000)),
                ('Medicine', models.CharField(max_length=2000)),
            ],
        ),
        migrations.CreateModel(
            name='Questions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=30)),
                ('Age', models.CharField(max_length=2)),
                ('Sex', models.CharField(max_length=15)),
                ('Place', models.CharField(max_length=50)),
                ('Email', models.CharField(max_length=30)),
                ('Phone', models.CharField(max_length=15)),
                ('Problem', models.CharField(max_length=2000)),
            ],
        ),
    ]
