# Generated by Django 3.0.3 on 2020-08-04 09:20

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0002_answers_questions'),
    ]

    operations = [
        migrations.AddField(
            model_name='answers',
            name='patientname',
            field=models.CharField(default=django.utils.timezone.now, max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='answers',
            name='patientnumber',
            field=models.CharField(default=2, max_length=15),
            preserve_default=False,
        ),
    ]
